import type {
  AccessKey,
  Asset,
  CatalogStatus,
  ConfigSourceStatus,
  Credential,
  InstanceStatus,
  Session,
} from '@/domain'

export interface DemoFixtures {
  status: InstanceStatus
  assets: Asset[]
  credentials: Credential[]
  accessKeys: AccessKey[]
  sessions: Session[]
  configStatus: CatalogStatus
}

export function createDemoFixtures(): DemoFixtures {
  const sources: ConfigSourceStatus[] = [
    {
      sourceId: 'home',
      generation: 18,
      lastSuccessAt: '2026-08-14 09:41:22',
      lastSuccessRevision: 127,
      lastErrorAt: null,
      lastErrorCode: null,
      lastErrorMessage: null,
    },
    {
      sourceId: 'edge',
      generation: 7,
      lastSuccessAt: '2026-08-13 22:16:08',
      lastSuccessRevision: 121,
      lastErrorAt: '2026-08-14 09:43:10',
      lastErrorCode: 'unknown_reference',
      lastErrorMessage: 'asset edge-router references a missing credential',
    },
  ]

  return {
    status: {
      status: 'ok',
      version: '0.2.1-demo',
      catalogRevision: 128,
    },
    assets: [
      {
        id: 'asset-prod-gateway',
        name: 'prod-gateway',
        protocol: 'ssh',
        hostname: '10.24.0.12',
        port: 22,
        description: 'Production ingress host',
        tags: ['production', 'edge'],
        credentialId: 'credential-deploy',
        createdAt: '2026-07-28 14:20:00',
        updatedAt: '2026-08-14 09:41:22',
        management: { mode: 'config', sourceId: 'home', sourceKey: 'asset/prod-gateway' },
        health: {
          status: 'healthy',
          checkedAt: '2026-08-14 09:47:52',
          lastSuccessAt: '2026-08-14 09:47:52',
          latencyMs: 24,
        },
      },
      {
        id: 'asset-homelab-nas',
        name: 'homelab-nas',
        protocol: 'ssh',
        hostname: '192.168.50.15',
        port: 22,
        description: 'Storage and backup host',
        tags: ['home', 'storage'],
        credentialId: 'credential-homelab',
        createdAt: '2026-08-02 18:12:40',
        updatedAt: '2026-08-09 07:31:15',
        management: { mode: 'local' },
        health: {
          status: 'healthy',
          checkedAt: '2026-08-14 09:47:40',
          lastSuccessAt: '2026-08-14 09:47:40',
          latencyMs: 4,
        },
      },
      {
        id: 'asset-router-ui',
        name: 'router-ui',
        protocol: 'tcp',
        hostname: '192.168.50.1',
        port: 443,
        description: 'OpenWrt management endpoint',
        tags: ['home', 'network'],
        credentialId: null,
        createdAt: '2026-08-04 11:06:33',
        updatedAt: '2026-08-04 11:06:33',
        management: { mode: 'local' },
        health: {
          status: 'failed',
          checkedAt: '2026-08-14 09:46:58',
          lastSuccessAt: '2026-08-14 08:52:09',
          errorCode: 'connection_refused',
          errorMessage: 'The target refused the TCP connection.',
        },
      },
      {
        id: 'asset-build-runner',
        name: 'build-runner',
        protocol: 'ssh',
        hostname: '10.24.2.31',
        port: 2222,
        description: null,
        tags: ['ci'],
        credentialId: 'credential-deploy',
        createdAt: '2026-08-11 08:03:12',
        updatedAt: '2026-08-14 09:41:22',
        management: { mode: 'config', sourceId: 'home', sourceKey: 'asset/build-runner' },
        health: { status: 'unknown', checkedAt: null },
      },
      {
        id: 'asset-bastion-01',
        name: 'bastion-01',
        protocol: 'ssh',
        hostname: '10.24.0.8',
        port: 22,
        description: 'Operations entry host',
        tags: ['production', 'access'],
        credentialId: 'credential-deploy',
        createdAt: '2026-08-01 10:18:22',
        updatedAt: '2026-08-13 16:30:04',
        management: { mode: 'config', sourceId: 'home', sourceKey: 'asset/bastion-01' },
        health: {
          status: 'healthy',
          checkedAt: '2026-08-14 09:47:48',
          lastSuccessAt: '2026-08-14 09:47:48',
          latencyMs: 18,
        },
      },
      {
        id: 'asset-git-server',
        name: 'git-server',
        protocol: 'ssh',
        hostname: '10.24.1.20',
        port: 22,
        description: 'Internal source mirror',
        tags: ['development'],
        credentialId: 'credential-deploy',
        createdAt: '2026-08-03 12:08:19',
        updatedAt: '2026-08-12 15:20:31',
        management: { mode: 'local' },
        health: {
          status: 'healthy',
          checkedAt: '2026-08-14 09:47:34',
          lastSuccessAt: '2026-08-14 09:47:34',
          latencyMs: 11,
        },
      },
      {
        id: 'asset-metrics-api',
        name: 'metrics-api',
        protocol: 'tcp',
        hostname: '10.24.3.14',
        port: 9090,
        description: 'Metrics ingestion endpoint',
        tags: ['observability'],
        credentialId: null,
        createdAt: '2026-08-05 09:14:40',
        updatedAt: '2026-08-05 09:14:40',
        management: { mode: 'config', sourceId: 'home', sourceKey: 'asset/metrics-api' },
        health: {
          status: 'healthy',
          checkedAt: '2026-08-14 09:47:26',
          lastSuccessAt: '2026-08-14 09:47:26',
          latencyMs: 8,
        },
      },
      {
        id: 'asset-cache-01',
        name: 'cache-01',
        protocol: 'tcp',
        hostname: '10.24.3.21',
        port: 6379,
        description: 'Shared cache endpoint',
        tags: ['production', 'data'],
        credentialId: null,
        createdAt: '2026-08-06 17:43:05',
        updatedAt: '2026-08-13 21:11:55',
        management: { mode: 'local' },
        health: {
          status: 'healthy',
          checkedAt: '2026-08-14 09:47:22',
          lastSuccessAt: '2026-08-14 09:47:22',
          latencyMs: 7,
        },
      },
      {
        id: 'asset-staging-node',
        name: 'staging-node',
        protocol: 'ssh',
        hostname: '10.24.4.18',
        port: 22,
        description: 'Staging application host',
        tags: ['staging'],
        credentialId: 'credential-deploy',
        createdAt: '2026-08-08 13:22:11',
        updatedAt: '2026-08-14 08:03:44',
        management: { mode: 'local' },
        health: { status: 'unknown', checkedAt: null },
      },
      {
        id: 'asset-dns-service',
        name: 'dns-service',
        protocol: 'tcp',
        hostname: '192.168.50.2',
        port: 53,
        description: 'Local resolver endpoint',
        tags: ['home', 'network'],
        credentialId: null,
        createdAt: '2026-08-10 06:45:32',
        updatedAt: '2026-08-10 06:45:32',
        management: { mode: 'config', sourceId: 'home', sourceKey: 'asset/dns-service' },
        health: {
          status: 'healthy',
          checkedAt: '2026-08-14 09:47:13',
          lastSuccessAt: '2026-08-14 09:47:13',
          latencyMs: 3,
        },
      },
    ],
    credentials: [
      {
        id: 'credential-homelab',
        name: 'homelab-root',
        username: 'root',
        authType: 'password',
        password: 'configured',
        privateKey: 'missing',
        passphrase: 'missing',
        management: { mode: 'local' },
      },
      {
        id: 'credential-deploy',
        name: 'deploy-key',
        username: 'deploy',
        authType: 'key_passphrase',
        password: 'missing',
        privateKey: 'configured',
        passphrase: 'configured',
        management: { mode: 'config', sourceId: 'home', sourceKey: 'credential/deploy-key' },
      },
    ],
    accessKeys: [
      {
        id: 'access-oslo-laptop',
        name: 'oslo-laptop',
        fingerprint: 'SHA256:n7H0PdemoLaptopC8K4a',
        enabled: true,
        accessMode: 'all',
        assetIds: null,
        management: { mode: 'local' },
      },
      {
        id: 'access-ci-deploy',
        name: 'ci-deploy',
        fingerprint: 'SHA256:b91H0PdemoCiZ2F6s',
        enabled: true,
        accessMode: 'restricted',
        assetIds: ['asset-build-runner', 'asset-prod-gateway'],
        management: { mode: 'config', sourceId: 'home', sourceKey: 'access/ci-deploy' },
      },
      {
        id: 'access-retired-tablet',
        name: 'retired-tablet',
        fingerprint: 'SHA256:d3m0RetiredKey4S2x',
        enabled: false,
        accessMode: 'restricted',
        assetIds: [],
        management: { mode: 'local' },
      },
    ],
    sessions: [
      {
        id: 'session-active-shell',
        keyFingerprint: 'SHA256:n7H0PdemoLaptopC8K4a',
        keyName: 'oslo-laptop',
        mode: 'direct',
        assetName: 'homelab-nas',
        targetHost: '192.168.50.15',
        targetPort: 22,
        clientIp: '192.168.50.42',
        status: 'started',
        error: null,
        startedAt: '2026-08-14 09:35:11',
        endedAt: null,
      },
      {
        id: 'session-ci-sftp',
        keyFingerprint: 'SHA256:b91H0PdemoCiZ2F6s',
        keyName: 'ci-deploy',
        mode: 'sftp',
        assetName: 'build-runner',
        targetHost: '10.24.2.31',
        targetPort: 2222,
        clientIp: '10.24.8.20',
        status: 'ok',
        error: null,
        startedAt: '2026-08-14 09:18:02',
        endedAt: '2026-08-14 09:20:48',
      },
      {
        id: 'session-denied-forward',
        keyFingerprint: 'SHA256:d3m0RetiredKey4S2x',
        keyName: 'retired-tablet',
        mode: 'tcp-forward',
        assetName: 'router-ui',
        targetHost: '192.168.50.1',
        targetPort: 443,
        clientIp: '192.168.50.81',
        status: 'failed',
        error: 'asset access denied',
        startedAt: '2026-08-14 08:58:43',
        endedAt: '2026-08-14 08:58:43',
      },
    ],
    configStatus: {
      revision: 128,
      manifestApiVersion: 'hop/v1alpha1',
      sources,
      orphans: [
        {
          resourceType: 'asset',
          sourceId: 'edge',
          sourceKey: 'asset/old-proxy',
          orphanedAt: '2026-08-13 22:16:08',
        },
      ],
    },
  }
}
